### PR TITLE
Make plot rating prettier

### PR DESCRIPTION
**Pull request by jacklee1792**
Before:

image

After:

image

### CODE REVIEW

**Comment by jacklee1792** [comment]
Some other small tweaks:

- Remove `idna==3.1` from `requirements.txt` because it conflicts with a `requests` dependency
- Support loading environment variables from `.env`
- Add `.gitkeep` to `/graphs` so plotting functions have a place to store graphs as a file
- Add some more things to `.gitignore`

**Comment by jtyliu** [comment]
Remove the dotenv

**Comment by jacklee1792** [comment]
Done

**Comment by jtyliu** [comment]
Thanks!

**Pull request merged**
